services:
  freshemeatretailer:
    container_name: freshemeatretailercontainer
    build: .
    image: freshemeatretailer:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
